name: masa_epico_concrete_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cool_alert: ^2.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.5
  injector: ^3.0.0
  path: ^1.8.3
  pocketbase: ^0.18.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true
  fonts:    
  - family: Heebo
    fonts:
      - asset: fonts/Heebo-Regular.ttf
  assets: 
    - images/epico-logo.jpg
    - dev.env
